name: Test

on: pull_request

jobs:
  test:
    name: Run full tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        pytthon: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: ${{ matrix.python }}
      - name: Install apt packages
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev
      - name: Run test suite
        run: python${{ matrix.python }} -m tornado.test
